### ISSUE TITLE
tmux-continuum

### ISSUE THREAD

**Issue by alex-popov-tech** [eduncan911/dotfiles#4]
Hello! Your dotfiles looks really nice, and i see here tmux-continuum plugin https://github.com/eduncan911/dotfiles/blob/master/.tmux.conf#L50 but it is disabled right now...does it work for you?

**Comment by eduncan911** [comment]
I originally disabled it because I do recall:

* there were a few times it was not saved
* a few saves was completely empty/blank, forcing me to restore a backup I had.  (see below why this happened more than enough times)
* the `restore` feature had many issues, and I just always resorted back to CTRL-B-R to restore
* i lost "backups" because of the auto-save every 15 minutes quickly pushes out the oldest 10 versions
* I don't always want to restore my sessions...
* a few command line passwords have accidentally been recorded with the auto-saves, where I would have abandoned the session instead.
* most annoying, my work laptops have digital guardian installed - which is a security file inspector, which greatly slows down startup and saves - like 30 seconds to a minute each!  having control over when it does save, or restores, is paramount.

Why blank sessions?  Because I often start tmux with an instantaneous empty session for speed - and often times I don't want to restore the entire tree.  With `auto-save` enabled, this quickly overwrites my previous saves!

Also, sometimes I would start tmux - with the intension to restore.  it didn't auto-restore, and sat blank/empty.  Auto-save kicked in, and recorded a Blank restore file.  All before I was able to get back to my terminal.  That was painful...

So in the end, I actually like the workflow of "saving when I think of it" because my workflow is pretty much only a single session or two at a time, and then done.  This affords me the flexibility of thinking, "do I really want to keep what I just did today?  nah, that was junk." and just kill tmux, no save.  

Saves are easy enough with ctrl-b + s.  

---

As a final note: I've been experimenting with multiple tmux conf files - that points to different save directories.  this allows me to have a couple for coding/FOSS stuff.  a couple of other sessions related to microprocessor debugging (and always attach and debug with windows/panes auto-set), as well as special sessions for work -vs- home things.

it's still a bit too much to manage - have one large tmux running with 18+ sessions seems to be easiest.  just, that's a lot to save and restore all the time.
